// const products = [
//   {
//     id: 1,
//     categoryId: 1,
//     subCategory: "AI",
//     img: "/assets/img/book/প্রম্পট ইঞ্জিনিয়ারিং.png",
//     author: "এনামুল হক",
//     title: "প্রম্পট ইঞ্জিনিয়ারিং",
//     subtitle: "হার্ডকভার",
//     rating: "৪.৫",
//     oldPrice: "৬00",
//     price: "৫১৬",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.30s",
//     inStock: true,
//     bookTotalPage: "৫০০",
//     isNewBook: true,
//     isUpcomingBook: true,
//     isBestSellingBook: true,
//     date: "November 21, 2024",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
//   {
//     id: 2,
//     categoryId: 1,
//     subCategory: "Data Science",
//     img: "/assets/img/book/data sience.jpg",
//     author: "Enamul Haque",
//     title: "A Beginner's Guide To Data Science",
//     subtitle: "হার্ডকভার",
//     rating: 2,
//     oldPrice: "৭০০",
//     price: "৪৯৯",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.40s",
//     inStock: true,
//     bookTotalPage: "৩০০",
//     isNewBook: true,
//     isUpcomingBook: true,
//     isBestSellingBook: true,
//     date: "January 12, 2025",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
//   {
//     id: 3,
//     categoryId: 2,
//     subCategory: "Mindset",
//     img: "/assets/img/book/mindmaping.png",
//     author: "সাইফুল লানজু",
//     title: "মাইন্ড ম্যাপিং",
//     subtitle: "হার্ডকভার",
//     rating: "৪.৫",
//     oldPrice: "৫৫০",
//     price: "৪৯২",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.50s",
//     inStock: true,
//     bookTotalPage: "২০০",
//     isNewBook: false,
//     isUpcomingBook: false,
//     isBestSellingBook: false,
//     date: "february 10, 2025",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
//   {
//     id: 4,
//     categoryId: 3,
//     subCategory: "Romantic",
//     img: "/assets/img/book/Goti Bati Sanki copy.eps 2 copy.jpg",
//     author: "সারোয়ার জাহান",
//     title: "ঘটি বাটি সানকি",
//     subtitle: "হার্ডকভার",
//     rating: "৪.৫",
//     oldPrice: "৪00",
//     price: "৩৪৪",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.60s",
//     inStock: true,
//     bookTotalPage: "১৫০",
//     isNewBook: true,
//     isUpcomingBook: true,
//     isBestSellingBook: true,
//     date: "March 12, 2025",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
//   {
//     id: 5,
//     categoryId: 4,
//     subCategory: "Modern Poetry",
//     img: "/assets/img/book/nirostropodaboli.png",
//     author: "হেলাল মুহাম্মদ",
//     title: "নিরস্ত্র পদাবলী",
//     subtitle: "হার্ডকভার",
//     rating: "৪.৫",
//     oldPrice: "২00",
//     price: "১৭২",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.70s",
//     inStock: true,
//     bookTotalPage: "৫০০",
//     isNewBook: false,
//     isUpcomingBook: false,
//     isBestSellingBook: false,
//     date: "April 12, 2025",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
//   {
//     id: 6,
//     categoryId: 4,
//     subCategory: "Classic Poetry",
//     img: "/assets/img/book/sotti sundor copy.jpg",
//     author: "Mozammel Haque (Maruf)",
//     title: "সত্যই সুন্দর",
//     subtitle: "হার্ডকভার",
//     rating: "৪.৫",
//     oldPrice: "২৫০",
//     price: "১৯০",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.80s",
//     inStock: false,
//     bookTotalPage: "৪০০",
//     isNewBook: true,
//     isUpcomingBook: true,
//     isBestSellingBook: true,
//     date: "May 12, 2025",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
//   {
//     id: 7,
//     categoryId: 5,
//     subCategory: "Short Story",
//     img: "/assets/img/book/no identiry.jpg",
//     author: "সারোয়ার জাহান",
//     title: "নো আইডেন্টিটি",
//     subtitle: "হার্ডকভার",
//     rating: "৪.৫",
//     oldPrice: "৩০০",
//     price: "২২৫",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.90s",
//     inStock: true,
//     bookTotalPage: "২৫০",
//     isNewBook: false,
//     isUpcomingBook: false,
//     isBestSellingBook: false,
//     date: "June 12, 2025",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
//   {
//     id: 8,
//     categoryId: 6,
//     subCategory: "Labor Law",
//     img: "/assets/img/book/default-produt-image.jpg",
//     author: "মুহাম্মাদ মাহবুবুল হাসান",
//     title: "কর্মক্ষেত্রে দুর্ঘটনা আইন",
//     subtitle: "হার্ডকভার",
//     rating: "৪.৫",
//     oldPrice: "৫৫০",
//     price: "৪১২",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.60s",
//     inStock: true,
//     bookTotalPage: "৫০০",
//     isNewBook: true,
//     isUpcomingBook: true,
//     isBestSellingBook: true,
//     date: "November 12, 2025",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
//   {
//     id: 9,
//     categoryId: 7,
//     subCategory: "Macroeconomics",
//     img: "/assets/img/book/default-produt-image.jpg",
//     author: "ড. মোঃ আইনুল ইসলাম",
//     title: "নোবেল বিজয়ী অর্থনীতি",
//     subtitle: "হার্ডকভার",
//     rating: "৪.৫",
//     oldPrice: "৬৬৫",
//     price: "৫০০",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.60s",
//     inStock: true,
//     bookTotalPage: "১০০",
//     isNewBook: true,
//     isUpcomingBook: true,
//     isBestSellingBook: true,
//     date: "Auguest 12, 2025",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
//   {
//     id: 10,
//     categoryId: 8,
//     subCategory: "Quran Study",
//     img: "/assets/img/book/poshchima apottir shathe bahas.jpg",
//     author: "মুসা আল হাফিজ",
//     title: "আল-কুরআন অধ্যয়ন",
//     subtitle: "হার্ডকভার",
//     rating: "৪.৫",
//     oldPrice: "৬৬৫",
//     price: "৫০০",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.60s",
//     inStock: true,
//     bookTotalPage: "৫০০",
//     isNewBook: true,
//     isUpcomingBook: true,
//     isBestSellingBook: true,
//     date: "April 12, 2026",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
//   {
//     id: 11,
//     categoryId: 9,
//     subCategory: "Grammar",
//     img: "/assets/img/book/GRAMMARGENERAL MASTER.png",
//     author: "Mozammel Haque (Maruf)",
//     title: "General Master Grammar",
//     subtitle: "Paperback",
//     rating: "৪.৫",
//     oldPrice: "৬৯৯",
//     price: "৫২৫",
//     badge: ["Hot", "-২৫%"],
//     delay: "0.60s",
//     inStock: true,
//     bookTotalPage: "২৮০",
//     isNewBook: true,
//     isUpcomingBook: true,
//     isBestSellingBook: true,
//     date: "July 03, 2026",
//     descriptions:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
//   },
// ];

// export default products;

const products = [
  {
    id: 1,
    categoryId: 1,
    subCategory: "AI",
    img: "/assets/img/book/প্রম্পট ইঞ্জিনিয়ারিং.png",
    authorId: 1,
    title: "প্রম্পট ইঞ্জিনিয়ারিং",
    subtitle: "হার্ডকভার",
    rating: 4.5,
    oldPrice: 600,
    price: 516,
    badge: ["Hot", "-২৫%"],
    delay: "0.30s",
    inStock: true,
    bookTotalPage: 500,
    isNewBook: true,
    isUpcomingBook: true,
    isBestSellingBook: true,
    date: "November 21, 2024",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
  {
    id: 2,
    categoryId: 1,
    subCategory: "Data Science",
    img: "/assets/img/book/data sience.jpg",
    authorId: 1,
    title: "A Beginner's Guide To Data Science",
    subtitle: "হার্ডকভার",
    rating: 2,
    oldPrice: 700,
    price: 499,
    badge: ["Hot", "-২৫%"],
    delay: "0.40s",
    inStock: true,
    bookTotalPage: 300,
    isNewBook: true,
    isUpcomingBook: true,
    isBestSellingBook: true,
    date: "January 12, 2025",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
  {
    id: 3,
    categoryId: 2,
    subCategory: "Mindset",
    img: "/assets/img/book/mindmaping.png",
    authorId: 2,
    title: "মাইন্ড ম্যাপিং",
    subtitle: "হার্ডকভার",
    rating: "৪.৫",
    oldPrice: 550,
    price: 492,
    badge: ["Hot", "-২৫%"],
    delay: "0.50s",
    inStock: true,
    bookTotalPage: 200,
    isNewBook: false,
    isUpcomingBook: false,
    isBestSellingBook: false,
    date: "february 10, 2025",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
  {
    id: 4,
    categoryId: 3,
    subCategory: "Romantic",
    img: "/assets/img/book/Goti Bati Sanki copy.eps 2 copy.jpg",
    authorId: 3,
    title: "ঘটি বাটি সানকি",
    subtitle: "হার্ডকভার",
    rating: "৪.৫",
    oldPrice: 400,
    price: 344,
    badge: ["Hot", "-২৫%"],
    delay: "0.60s",
    inStock: true,
    bookTotalPage: 150,
    isNewBook: true,
    isUpcomingBook: true,
    isBestSellingBook: true,
    date: "March 12, 2025",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
  {
    id: 5,
    categoryId: 4,
    subCategory: "Modern Poetry",
    img: "/assets/img/book/nirostropodaboli.png",
    authorId: 4,
    title: "নিরস্ত্র পদাবলী",
    subtitle: "হার্ডকভার",
    rating: "৪.৫",
    oldPrice: 200,
    price: 172,
    badge: ["Hot", "-২৫%"],
    delay: "0.70s",
    inStock: true,
    bookTotalPage: 500,
    isNewBook: false,
    isUpcomingBook: false,
    isBestSellingBook: false,
    date: "April 12, 2025",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
  {
    id: 6,
    categoryId: 4,
    subCategory: "Classic Poetry",
    img: "/assets/img/book/sotti sundor copy.jpg",
    authorId: 10,
    title: "সত্যই সুন্দর",
    subtitle: "হার্ডকভার",
    rating: "৪.৫",
    oldPrice: 250,
    price: 190,
    badge: ["Hot", "-২৫%"],
    delay: "0.80s",
    inStock: false,
    bookTotalPage: 400,
    isNewBook: true,
    isUpcomingBook: true,
    isBestSellingBook: true,
    date: "May 12, 2025",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
  {
    id: 7,
    categoryId: 5,
    subCategory: "Short Story",
    img: "/assets/img/book/no identiry.jpg",
    authorId: 3,
    title: "নো আইডেন্টিটি",
    subtitle: "হার্ডকভার",
    rating: "৪.৫",
    oldPrice: 300,
    price: 225,
    badge: ["Hot", "-২৫%"],
    delay: "0.90s",
    inStock: true,
    bookTotalPage: 250,
    isNewBook: false,
    isUpcomingBook: false,
    isBestSellingBook: false,
    date: "June 12, 2025",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
  {
    id: 8,
    categoryId: 6,
    subCategory: "Labor Law",
    img: "/assets/img/book/default-produt-image.jpg",
    authorId: 6,
    title: "কর্মক্ষেত্রে দুর্ঘটনা আইন",
    subtitle: "হার্ডকভার",
    rating: "৪.৫",
    oldPrice: 550,
    price: 412,
    badge: ["Hot", "-২৫%"],
    delay: "0.60s",
    inStock: true,
    bookTotalPage: 500,
    isNewBook: true,
    isUpcomingBook: true,
    isBestSellingBook: true,
    date: "November 12, 2025",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
  {
    id: 9,
    categoryId: 7,
    subCategory: "Macroeconomics",
    img: "/assets/img/book/default-produt-image.jpg",
    authorId: 7,
    title: "নোবেল বিজয়ী অর্থনীতি",
    subtitle: "হার্ডকভার",
    rating: "৪.৫",
    oldPrice: 665,
    price: 500,
    badge: ["Hot", "-২৫%"],
    delay: "0.60s",
    inStock: true,
    bookTotalPage: 100,
    isNewBook: true,
    isUpcomingBook: true,
    isBestSellingBook: true,
    date: "Auguest 12, 2025",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
  {
    id: 10,
    categoryId: 8,
    subCategory: "Quran Study",
    img: "/assets/img/book/poshchima apottir shathe bahas.jpg",
    authorId: 8,
    title: "আল-কুরআন অধ্যয়ন",
    subtitle: "হার্ডকভার",
    rating: "৪.৫",
    oldPrice: 665,
    price: 500,
    badge: ["Hot", "-২৫%"],
    delay: "0.60s",
    inStock: true,
    bookTotalPage: 500,
    isNewBook: true,
    isUpcomingBook: true,
    isBestSellingBook: true,
    date: "April 12, 2026",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
  {
    id: 11,
    categoryId: 9,
    subCategory: "Grammar",
    img: "/assets/img/book/GRAMMARGENERAL MASTER.png",
    authorId: 9,
    title: "General Master Grammar",
    subtitle: "Paperback",
    rating: "৪.৫",
    oldPrice: 699,
    price: 525,
    badge: ["Hot", "-২৫%"],
    delay: "0.60s",
    inStock: true,
    bookTotalPage: 280,
    isNewBook: true,
    isUpcomingBook: true,
    isBestSellingBook: true,
    date: "July 03, 2026",
    descriptions:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit purus vel, of Link viveirra facilisi neque quisque. Phasellus aliquam ut id rhoncus. In viverra sed vitae vivamus amet, nuncg vivamus. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus sit am.",
  },
];

export default products;
