# Generated by Django 6.0.6 on 2026-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banner_background_image', models.ImageField(upload_to='uploads/home/banner/background')),
                ('banner_image', models.ImageField(upload_to='uploads/home/banner/image')),
                ('banner_shape_image', models.ImageField(blank=True, null=True, upload_to='uploads/home/banner/shape')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=255)),
                ('feature_image_one', models.ImageField(upload_to='uploads/home/feature')),
                ('feature_image_two', models.ImageField(upload_to='uploads/home/feature')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_description', models.TextField(blank=True, null=True)),
                ('slider_image', models.ImageField(upload_to='uploads/home/slider')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'home',
            },
        ),
    ]
