# Generated by Django 6.0.6 on 2026-07-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsettings',
            old_name='company',
            new_name='company_name',
        ),
    ]
