# Generated by Django 6.0.6 on 2026-07-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_rename_company_generalsettings_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='privacy_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
