const products = [
  {
    id: 1,
    categoryId: 1,
    subCategory: "AI",
    img: "/assets/img/book/প্রম্পট ইঞ্জিনিয়ারিং.png",
    author: "এনামুল হক",
    title: "প্রম্পট ইঞ্জিনিয়ারিং",
    subtitle: "হার্ডকভার",
    rating: 4.5,
    oldPrice: 600,
    price: 516,
    badge: ["Hot", "-25%"],
    delay: "0.30s",
    inStock: true,
    date: "November 21, 2024",
  },
  {
    id: 2,
    categoryId: 1,
    subCategory: "Data Science",
    img: "/assets/img/book/data sience.jpg",
    author: "Enamul Haque",
    title: "A Beginner's Guide To Data Science",
    subtitle: "হার্ডকভার",
    rating: 2,
    oldPrice: 700,
    price: 499,
    badge: ["Hot", "-25%"],
    delay: "0.40s",
    inStock: true,
  },
  {
    id: 3,
    categoryId: 2,
    subCategory: "Mindset",
    img: "/assets/img/book/mindmaping.png",
    author: "সাইফুল লানজু",
    title: "মাইন্ড ম্যাপিং",
    subtitle: "হার্ডকভার",
    rating: 4.5,
    oldPrice: 550,
    price: 492,
    badge: ["Hot", "-25%"],
    delay: "0.50s",
    inStock: true,
  },
  {
    id: 4,
    categoryId: 3,
    subCategory: "Romantic",
    img: "/assets/img/book/Goti Bati Sanki copy.eps 2 copy.jpg",
    author: "সারোয়ার জাহান",
    title: "ঘটি বাটি সানকি",
    subtitle: "হার্ডকভার",
    rating: 4.5,
    oldPrice: 400,
    price: 344,
    badge: ["Hot", "-25%"],
    delay: "0.60s",
    inStock: true,
  },
  {
    id: 5,
    categoryId: 4,
    subCategory: "Modern Poetry",
    img: "/assets/img/book/nirostropodaboli.png",
    author: "হেলাল মুহাম্মদ",
    title: "নিরস্ত্র পদাবলী",
    subtitle: "হার্ডকভার",
    rating: 4.5,
    oldPrice: 200,
    price: 172,
    badge: ["Hot", "-25%"],
    delay: "0.70s",
    inStock: true,
  },
  {
    id: 6,
    categoryId: 4,
    subCategory: "Classic Poetry",
    img: "/assets/img/book/sotti sundor copy.jpg",
    author: "Mozammel Haque (Maruf)",
    title: "সত্যই সুন্দর",
    subtitle: "হার্ডকভার",
    rating: 4.5,
    oldPrice: 250,
    price: 190,
    badge: ["Hot", "-25%"],
    delay: "0.80s",
    inStock: false,
  },
  {
    id: 7,
    categoryId: 5,
    subCategory: "Short Story",
    img: "/assets/img/book/no identiry.jpg",
    author: "সারোয়ার জাহান",
    title: "নো আইডেন্টিটি",
    subtitle: "হার্ডকভার",
    rating: 4.5,
    oldPrice: 300,
    price: 225,
    badge: ["Hot", "-25%"],
    delay: "0.90s",
    inStock: true,
  },
  {
    id: 8,
    categoryId: 6,
    subCategory: "Labor Law",
    img: "/assets/img/book/default-produt-image.jpg",
    author: "মুহাম্মাদ মাহবুবুল হাসান",
    title: "কর্মক্ষেত্রে দুর্ঘটনা আইন",
    subtitle: "হার্ডকভার",
    rating: 4.5,
    oldPrice: 550,
    price: 412,
    badge: ["Hot", "-25%"],
    delay: "0.60s",
    inStock: true,
  },
  {
    id: 9,
    categoryId: 7,
    subCategory: "Macroeconomics",
    img: "/assets/img/book/default-produt-image.jpg",
    author: "ড. মোঃ আইনুল ইসলাম",
    title: "নোবেল বিজয়ী অর্থনীতি",
    subtitle: "হার্ডকভার",
    rating: 4.5,
    oldPrice: 665,
    price: 500,
    badge: ["Hot", "-25%"],
    delay: "0.60s",
    inStock: true,
  },
  {
    id: 10,
    categoryId: 8,
    subCategory: "Quran Study",
    img: "/assets/img/book/poshchima apottir shathe bahas.jpg",
    author: "মুসা আল হাফিজ",
    title: "আল-কুরআন অধ্যয়ন",
    subtitle: "হার্ডকভার",
    rating: 4.5,
    oldPrice: 665,
    price: 500,
    badge: ["Hot", "-25%"],
    delay: "0.60s",
    inStock: true,
  },
  {
    id: 11,
    categoryId: 9,
    subCategory: "Grammar",
    img: "/assets/img/book/GRAMMARGENERAL MASTER.png",
    author: "Mozammel Haque (Maruf)",
    title: "General Master Grammar",
    subtitle: "Paperback",
    rating: 4.5,
    oldPrice: 699,
    price: 525,
    badge: ["Hot", "-25%"],
    delay: "0.60s",
    inStock: true,
  },
];

export default products;
